name: Run Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './pair-words-fe/package-lock.json'

    - name: Install dependencies
      run: |
        cd pair-words-fe
        npm ci

    - name: Run tests
      run: |
        cd pair-words-fe
        npm test
